services:
  - type: web
    name: plant-disease-detector-api
    runtime: python
    buildCommand: python -m pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn.conf.py
    envVars:
      - key: CORS_ORIGINS
        sync: false
